---

ospf_config:
  pid: 1
  rid: 192.168.50.33
  interfaces:
    - interface: e1/1
      area: 0
    - interface: e1/2
      area: 0
    - interface: e1/3
      area: 0
    - interface: e1/4
      area: 0
  loopback:
    - interface: loopback0
      ip_addr: 1.0.0.3
      mask: 255.255.255.255
      area: 0
    - interface: loopback1
      ip_addr: 1.2.3.4
      mask: 255.255.255.255
      area: 0

bgp_config:
  layer: "spine"
  asn: 65002
  rid: 192.168.50.33
  neighbors:
    - neighbor: 1.0.0.4
      peer_asn: 65002
    - neighbor: 1.0.0.5
      peer_asn: 65002
    - neighbor: 1.0.0.6
      peer_asn: 65002
    - neighbor: 1.0.0.7
      peer_asn: 65002
  loopback:
    interface: loopback0

multicast:
  layer: "spine"
  rp_address: 1.2.3.4
  lo0_addr: 1.0.0.3
