---

interface_config:
  ietf-interfaces:interfaces:
    interface:
    - name: GigabitEthernet1
      description: MGMT
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 192.168.50.15
          netmask: 255.255.255.0
    - name: GigabitEthernet2
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.20.0.1
          netmask: 255.255.255.0
    - name: GigabitEthernet3
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.26.0.1
          netmask: 255.255.255.0
    - name: GigabitEthernet4
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.26.2.1
          netmask: 255.255.255.0
    - name: GigabitEthernet5
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.26.1.1
          netmask: 255.255.255.0

ospf_config:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-ospf:router-ospf:
      ospf:
        process-id:
        - id: 1
          mpls:
            ldp:
              autoconfig: {}
          network:
          - ip: 172.20.0.0
            wildcard: 0.0.0.255
            area: 0
          - ip: 172.26.0.0
            wildcard: 0.0.0.255
            area: 0
          - ip: 172.26.1.0
            wildcard: 0.0.0.255
            area: 0
          - ip: 172.26.2.0
            wildcard: 0.0.0.255
            area: 0
          router-id: 192.168.50.15