---

eigrp_config:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-eigrp:router-eigrp:
      eigrp:
        classic-mode:
        - autonomous-system: 1
          eigrp:
            router-id: 192.168.50.16
          network:
            address-wildcard:
            - ipv4-address: 172.26.0.0
              wildcard: 0.0.3.255
            - ipv4-address: 172.16.4.0
              wildcard: 0.0.0.255
            - ipv4-address: 172.30.2.0
              wildcard: 0.0.0.255

interface_config:
  ietf-interfaces:interfaces:
    interface:
    - name: GigabitEthernet1
      description: MGMT
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 192.168.50.16
          netmask: 255.255.255.0
    - name: GigabitEthernet2
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.16.4.2
          netmask: 255.255.255.0
    - name: GigabitEthernet3
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.30.2.2
          netmask: 255.255.255.0
    - name: GigabitEthernet4
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.26.1.1
          netmask: 255.255.255.0
    - name: GigabitEthernet5
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.26.2.1
          netmask: 255.255.255.0
    - name: GigabitEthernet6
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.26.3.1
          netmask: 255.255.255.0
    - name: GigabitEthernet7
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.26.0.1
          netmask: 255.255.255.0
