---

interface_config:
  ietf-interfaces:interfaces:
    interface:
    - name: GigabitEthernet1
      description: MGMT
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 192.168.50.39
          netmask: 255.255.255.0
    - name: GigabitEthernet2
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.16.1.1
          netmask: 255.255.255.0
    - name: GigabitEthernet3
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.21.0.2
          netmask: 255.255.255.0
    - name: Loopback0
      type: iana-if-type:softwareLoopback
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 22.22.22.22
          netmask: 255.255.255.255

mpls_config:
  vrfs:
    - vrf: CUSTOMER1
      rd: "100:1"
      interface: GigabitEthernet2
      intf_ip_addr: 172.16.1.1 255.255.255.0
      ospf_pid: 2
      ospf_rid: "22.22.22.22"
      ospf_network: 172.16.1.0 0.0.0.255
      ospf_area: 0

bgp_config:
  asn: 100
  neighbors:
    - neighbor: 11.11.11.11
    - neighbor: 33.33.33.33
    - neighbor: 44.44.44.44
  loopback: Loopback0

ospf_config:
  pid: 1
  rid: 192.168.50.39
  mpls: true
  networks:
    - "22.22.22.22 0.0.0.0 area 0"
    - "172.21.0.0 0.0.0.255 area 0"