---

interface_config:
  ietf-interfaces:interfaces:
    interface:
    - name: GigabitEthernet1
      description: MGMT
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 192.168.50.39
          netmask: 255.255.255.0
    - name: GigabitEthernet2
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.16.1.1
          netmask: 255.255.255.0
    - name: GigabitEthernet3
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 172.21.0.2
          netmask: 255.255.255.0
    - name: Loopback0
      type: iana-if-type:softwareLoopback
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 22.22.22.22
          netmask: 255.255.255.255

ospf_config:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-ospf:router-ospf:
      ospf:
        process-id:
        - id: 1
          mpls:
            ldp:
              autoconfig: {}
          network:
          - ip: 172.21.0.0
            wildcard: 0.0.0.255
            area: 0
          - ip: 22.22.22.22
            wildcard: 0.0.0.0
            area: 0
          redistribute:
            ospf:
            - process-id: 2
          router-id: 192.168.50.39
        - id: 2
          network:
          - ip: 172.16.1.0
            wildcard: 0.0.0.255
            area: 0
          redistribute:
            ospf:
            - process-id: 1