---

ospf_config:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-ospf:router-ospf:
      ospf:
        process-id:
        - id: 2
          network:
          - ip: 10.2.1.0
            wildcard: 0.0.0.255
            area: 0
          - ip: 10.2.2.0
            wildcard: 0.0.0.255
            area: 0
          - ip: 2.2.2.10
            wildcard: 0.0.0.0
            area: 0
          router-id: 192.168.50.20
   
interface_config:
  ietf-interfaces:interfaces:
    interface:
    - name: GigabitEthernet1
      description: MGMT
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 192.168.50.20
          netmask: 255.255.255.0
    - name: GigabitEthernet3
      description: "site2-dist1 Gi0/1"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.2.1.1
          netmask: 255.255.255.0
    - name: GigabitEthernet4
      description: "site2-dist2 Gi0/1"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.2.2.1
          netmask: 255.255.255.0
    - name: Loopback0
      type: iana-if-type:softwareLoopback
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 2.2.2.10
          netmask: 255.255.255.255

bgp_config:
  asn: 65041
  rid: 192.168.50.20
  neighbors:
    - neighbor: 2.2.2.11
      peer_asn: 65022
    - neighbor: 2.2.2.12
      peer_asn: 65023
  source: "Loopback0"

cdp_config:
  interfaces:
    - "GigabitEthernet2"
    - "GigabitEthernet3"
    - "GigabitEthernet4"

dmvpn:
  layer: "spoke"
  tunnel:
    ip_addr: 10.10.0.3 255.255.255.0
  isp_intf:
    interface: GigabitEthernet2
    description: "ISP Gi2"
    ip_addr: 172.16.2.2
    mask: 255.255.255.0
    gateway: 172.16.2.1
  hub:
    tun_addr: 10.10.0.1
    isp_addr: 172.16.0.2