---

eigrp_config:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-eigrp:router-eigrp:
      eigrp:
        classic-mode:
        - autonomous-system: 1
          eigrp:
            router-id: 192.168.50.18
          network:
            address-wildcard:
            - ipv4-address: 10.1.1.0
              wildcard: 0.0.0.255
            - ipv4-address: 10.1.2.0
              wildcard: 0.0.0.255
            - ipv4-address: 10.1.3.0
              wildcard: 0.0.0.255
            - ipv4-address: 1.1.1.10
              wildcard: 0.0.0.0

interface_config:
  ietf-interfaces:interfaces:
    interface:
    - name: GigabitEthernet1
      description: MGMT
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 192.168.50.18
          netmask: 255.255.255.0
    - name: GigabitEthernet2
      description: "site1-vedge1"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.1.1.2
          netmask: 255.255.255.0
    - name: GigabitEthernet3
      description: "site1-dist1 Gi0/1"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.1.2.1
          netmask: 255.255.255.0
    - name: GigabitEthernet4
      description: "site1-dist2 Gi0/1"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.1.3.1
          netmask: 255.255.255.0
    - name: Loopback0
      type: iana-if-type:softwareLoopback
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 1.1.1.10
          netmask: 255.255.255.255

bgp_config:
  asn: 65011
  rid: 192.168.50.18
  networks:
    - address: "10.1.1.0"
      mask: "255.255.255.0"
  neighbors:
    - neighbor: 1.1.1.11
      peer_asn: 65012
    - neighbor: 1.1.1.12
      peer_asn: 65013
  vedge_neighbor:
    - neighbor: "10.1.1.1"
      peer_asn: 65010

cdp_config:
  interfaces:
    - "GigabitEthernet2"
    - "GigabitEthernet3"
    - "GigabitEthernet4"