---

bgp_config:
  asn: 65031
  rid: 192.168.50.22
  networks:
    - address: "10.3.0.0"
      mask: "255.255.255.0"
  neighbors:
    - neighbor: 3.3.3.11
      peer_asn: 65032
    - neighbor: 3.3.3.12
      peer_asn: 65033
  vedge_neighbor:
    - neighbor: "10.3.0.1"
      peer_asn: 65030

ospf_config:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-ospf:router-ospf:
      ospf:
        process-id:
        - id: 3
          network:
          - ip: 10.3.1.0
            wildcard: 0.0.0.255
            area: 0
          - ip: 10.3.2.0
            wildcard: 0.0.0.255
            area: 0
          - ip: 3.3.3.10
            wildcard: 0.0.0.0
            area: 0
          router-id: 192.168.50.22

interface_config:
  ietf-interfaces:interfaces:
    interface:
    - name: GigabitEthernet1
      description: "MGMT"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 192.168.50.22
          netmask: 255.255.255.0
    - name: GigabitEthernet2
      description: "site3-vedge1 Gi4"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.3.0.2
          netmask: 255.255.255.0
    - name: GigabitEthernet3
      description: "site3-dist1 Gi0/1"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.3.1.1
          netmask: 255.255.255.0
    - name: GigabitEthernet4
      description: "site3-dist2 Gi0/1"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.3.2.1
          netmask: 255.255.255.0
    - name: Loopback0
      description: "Lo0"
      type: iana-if-type:softwareLoopback
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 3.3.3.10
          netmask: 255.255.255.255

