---

eigrp_config:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-eigrp:router-eigrp:
      eigrp:
        classic-mode:
        - autonomous-system: 1
          eigrp:
            router-id: 192.168.50.18
          network:
            address-wildcard:
            - ipv4-address: 10.1.2.0
              wildcard: 0.0.0.255
            - ipv4-address: 10.1.3.0
              wildcard: 0.0.0.255
            - ipv4-address: 1.1.1.10
              wildcard: 0.0.0.0

interface_config:
  ietf-interfaces:interfaces:
    interface:
    - name: GigabitEthernet1
      description: MGMT
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 192.168.50.18
          netmask: 255.255.255.0
    - name: GigabitEthernet3
      description: "site1-dist1 Gi0/1"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.1.2.1
          netmask: 255.255.255.0
    - name: GigabitEthernet4
      description: "site1-dist2 Gi0/1"
      type: iana-if-type:ethernetCsmacd
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.1.3.1
          netmask: 255.255.255.0
    - name: Loopback0
      type: iana-if-type:softwareLoopback
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 1.1.1.10
          netmask: 255.255.255.255

bgp_config:
  asn: 65041
  rid: 192.168.50.18
  neighbors:
    - neighbor: 1.1.1.11
      peer_asn: 65012
    - neighbor: 1.1.1.12
      peer_asn: 65013
  source: "Loopback0"

cdp_config:
  interfaces:
    - "GigabitEthernet2"
    - "GigabitEthernet3"
    - "GigabitEthernet4"

dmvpn:
  layer: "spoke"
  tunnel:
    ip_addr: 10.10.0.2 255.255.255.0
  isp_intf:
    interface: GigabitEthernet2
    description: "ISP Gi2"
    ip_addr: 172.16.1.2
    mask: 255.255.255.0
    gateway: 172.16.1.1
  hub:
    tun_addr: 10.10.0.1
    isp_addr: 172.16.0.2