
bgp_config:
  asn: 65033
  rid: 192.168.50.31
  networks:
    - address: "10.3.3.0"
      mask: "255.255.255.0"
  neighbors:
    - neighbor: 3.3.3.10
      peer_asn: 65041
    - neighbor: 3.3.3.11
      peer_asn: 65032
  source: "Loopback0"

ospf_config:
  pid: 3
  rid: 192.168.50.31
  networks:
    - "10.3.2.0 0.0.0.255 area 0"
    - "10.3.3.0 0.0.0.255 area 0"
    - "10.3.4.0 0.0.0.255 area 0"
    - "3.3.3.12 0.0.0.0 area 0"

interfaces:
  - interface: "Gi0/1"
    description: "site3-core1 Gi4"
    ip: "10.3.2.2 255.255.255.0"
  - interface: "Gi0/2"
    description: "site3-dist1 Gi0/2"
    ip: "10.3.4.2 255.255.255.0"
  - interface: "Gi0/3"
    description: "10.3.3.0/24"
    ip: "10.3.3.1 255.255.255.0"
  - interface: "Lo0"
    description: "Lo0"
    ip: "3.3.3.12 255.255.255.255"

cdp_config:
  interfaces:
    - "Gi0/1"
    - "Gi0/2"