---
# tasks file for eigrp_role


- name: "Setup EIGRP"
  uri:
    url: "https://{{ansible_host}}/restconf/data/native/router/"
    method: put
    user: "{{ansible_user}}"
    password: "{{ansible_password}}"
    return_content: yes
    body: "{{eigrp_config}}"
    body_format: json
    validate_certs: false
    headers:
      Accept:
        application/yang-data+json
      Content-Type: "application/yang-data+json"
    status_code:
      - 200
      - 204