---

- name: "Setup Leaf TCAM"
  hosts: leaf
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Setup TCAM"
      cisco.nxos.nxos_config:
        lines:
          - hardware access-list tcam region vpc-convergence 0
          - hardware access-list tcam region arp-ether 256
          - copy running-config startup-config

    - name: "Reboot"
      cisco.nxos.nxos_reboot:
        confirm: true