---

dc-core1:
  platform: "ios"
  hostname: "192.168.50.23"
  groups:
    - cisco
  data:
    location: dc-core
    restconf: True
    model: 8000v

site1-core1:
  platform: "ios"
  hostname: "192.168.50.18"
  groups:
    - cisco
    - site1-core
  data:
    location: site1-core
    restconf: True
    model: 8000v

site1-dist1:
  platform: "ios"
  hostname: "192.168.50.26"
  groups:
    - cisco
    - site1-dist
  data:
    location: site1-dist
    restconf: False
    model: vIOS

site1-dist2:
  platform: "ios"
  hostname: "192.168.50.27"
  groups:
    - cisco
    - site1-dist
  data:
    location: site1-dist
    restconf: False
    model: vIOS


site2-core1:
  platform: "ios"
  hostname: "192.168.50.20"
  groups:
    - cisco
    - site2-core
  data:
    location: site2-core
    restconf: True
    ospf: True
    model: 8000v

site2-dist1:
  platform: "ios"
  hostname: "192.168.50.28"
  groups:
    - cisco
    - site2-dist
  data:
    location: site2-dist
    ospf: True
    restconf: False
    model: vIOS

site2-dist2:
  platform: "ios"
  hostname: "192.168.50.29"
  groups:
    - cisco
    - site2-dist
  data:
    location: site2-dist
    ospf: True
    restconf: False
    model: vIOS


site3-core1:
  platform: "ios"
  hostname: "192.168.50.22"
  groups:
    - cisco
    - site3-core
  data:
    location: site3-core
    restconf: True
    ospf: True
    model: 8000v

site3-dist1:
  platform: "ios"
  hostname: "192.168.50.30"
  groups:
    - cisco
    - site3-dist
  data:
    location: site3-dist
    ospf: True
    restconf: False
    model: vIOS

site3-dist2:
  platform: "ios"
  hostname: "192.168.50.31"
  groups:
    - cisco
    - site3-dist
  data:
    location: site3-dist
    ospf: True
    restconf: False
    model: vIOS
